# Generated by Django 2.2 on 2019-04-09 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fromtable',
            name='id',
        ),
        migrations.AddField(
            model_name='fromtable',
            name='object_id',
            field=models.CharField(default='', max_length=50, primary_key=True, serialize=False),
        ),
    ]
